name = "SparseMatrixIdentification"
uuid = "2607229e-3272-44a7-bc4a-cd97a328dfbf"
authors = ["Anastasia Dunca"]
version = "1.0.0-DEV"

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
